In [1]:
#in NN we have hidden layer, in other ML we dont have hidden layers where weights are directly being minimised using cost functions.
#each i/p values (perceptron) has nodes includes hidden layers, that calculates weights separately for indivdual obs but in ML it done in avg
import warnings
warnings.filterwarnings("ignore") # Don't want to see the warnings in the notebook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv(r"C:\Users\karthick's\Desktop\Jupyter\KSR\Churn_Modelling.csv")

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [40]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [41]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [42]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [43]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [44]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [45]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
#sequential module - intialize the nn
#dense module - to build layers of ANN

In [46]:
import tensorflow

In [47]:
import theano

In [48]:
# Initialising the ANN
classifier = Sequential()

In [49]:
#This is using Stochastic Gradient method in neural network, is thr any other methods available ? - batching Gradient descent
#Hidden layer uses Recctifier Activation function and Output layer uses Sigmoid Activation function.
#Basically several ways on updating the weights, here the learning rates decides by how much we update weights.

In [51]:
# output_dim - 'no of i/p and o/p var divide by 2', init - 'first hidden layer start with random 0 weights'
# activation - 'rectifier function' input_dim - 'no of i/p vars'
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 5, init = 'uniform', activation = 'relu', input_dim = 10))

In [52]:
#in first hidden layer, it doesnt know how many i/p nodes exists so we specify the input_dim, but in 2nd hidden layer since
###it is already exists in 1st hidden layer, it can recognise 
# Adding the second hidden layer
classifier.add(Dense(output_dim = 5, init = 'uniform', activation = 'relu'))

In [53]:
#Softmax activation function, when dependent var has more than two categories - also like sigmoid func
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

In [54]:
#Basically applying stochastic gradient descent (SGD) of whole ANN
#optimizer - algorithm to use, to find the optimal set of weights in NN - bcz so far we just initialised weights (SGD)
#'adam' - one of the SGD
#if we do classification, loss func can be the logarithmic loss (fyi: in regressor it is SSE) 
#if we use more than two categories,then loss function to use is categorical_crossentropy

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [55]:
#Now we apply our ANN to training set and see how at epoch the training accuracy is improved using ANN build network

In [56]:
#updating the weights after a batch of observations
#by experiment need to find the optimal batch size and no of epoch, there is no thumb rule of optimal values
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)




Epoch 1/100





8000/8000 [==============================] - 11s 1ms/step - loss: 0.4855 - acc: 0.7944
Epoch 2/100
8000/8000 [==============================] - 3s 380us/step - loss: 0.4353 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 313us/step - loss: 0.4305 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 278us/step - loss: 0.4259 - acc: 0.8066
Epoch 5/100
8000/8000 [==============================] - 2s 288us/step - loss: 0.4228 - acc: 0.8221
Epoch 6/100
8000/8000 [==============================] - 2s 279us/step - loss: 0.4203 - acc: 0.8262
Epoch 7/100
8000/8000 [==============================] - 2s 272us/step - loss: 0.4185 - acc: 0.8286
Epoch 8/100
8000/8000 [==============================] - 2s 275us/step - loss: 0.4170 - acc: 0.8302
Epoch 9/100
8000/8000 [==============================] - 2s 287us/step - loss: 0.4154 - acc: 0.8316
Epoch 10/100
8000/8000 [==============================] - 2s 301us/step - loss: 0.4148 - acc:

8000/8000 [==============================] - 2s 260us/step - loss: 0.3951 - acc: 0.8366
Epoch 67/100
8000/8000 [==============================] - 2s 252us/step - loss: 0.3952 - acc: 0.8354
Epoch 68/100
8000/8000 [==============================] - 2s 252us/step - loss: 0.3951 - acc: 0.8369
Epoch 69/100
8000/8000 [==============================] - 2s 257us/step - loss: 0.3949 - acc: 0.8371
Epoch 70/100
8000/8000 [==============================] - 2s 257us/step - loss: 0.3956 - acc: 0.8357
Epoch 71/100
8000/8000 [==============================] - 2s 279us/step - loss: 0.3947 - acc: 0.8380
Epoch 72/100
8000/8000 [==============================] - 2s 264us/step - loss: 0.3945 - acc: 0.8360
Epoch 73/100
8000/8000 [==============================] - 2s 237us/step - loss: 0.3948 - acc: 0.8359
Epoch 74/100
8000/8000 [==============================] - 2s 269us/step - loss: 0.3949 - acc: 0.8386
Epoch 75/100
8000/8000 [==============================] - 2s 261us/step - loss: 0.3946 - acc: 0.8377
Epo

In [62]:
# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [63]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [64]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [65]:
cm

array([[1559,   36],
       [ 278,  127]], dtype=int64)